---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: clean-completed-job-roles
rules:
- apiGroups: ["", "extensions", "apps", "batch"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: clean-completed-job-roleBinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: sa-clean-completed-job
  namespace: default
roleRef:
  kind: Role
  name: clean-completed-job-roles
  apiGroup: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-clean-completed-job
  namespace: default
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: clean-completed-job-cronjob
  namespace: default
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: sa-clean-completed-job
          containers:
          - name: kubectl
            image: wernight/kubectl
            command: 
            - /bin/sh
            - -c
            - kubectl delete job $(kubectl get jobs | awk '$3 ~ 1' | awk '{print $1}')         
          restartPolicy: OnFailure
